# Generated by Django 3.0 on 2020-02-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbAdmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentresponse',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
