# Generated by Django 3.0 on 2020-02-05 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbAdmin', '0002_commentresponse_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentresponse',
            name='title',
            field=models.TextField(max_length=120, unique=True),
        ),
    ]
