# Generated by Django 3.0 on 2020-02-05 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbAdmin', '0003_auto_20200205_0304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentResponse',
        ),
    ]
