# Generated by Django 3.0 on 2019-12-30 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0004_auto_20191224_0012'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentbox',
            options={'get_latest_by': 'created'},
        ),
        migrations.AlterModelOptions(
            name='notificationlist',
            options={'get_latest_by': 'created'},
        ),
    ]
