# Generated by Django 3.0 on 2020-01-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0005_auto_20191230_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentbox',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='notificationlist',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
