# Generated by Django 3.0 on 2020-01-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentbox', '0007_auto_20200120_0146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlist',
            name='type',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
