# Generated by Django 3.0 on 2019-12-30 02:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('1ae0767e-c7bc-4d01-8d50-58dec66c563e'), primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
