# Generated by Django 3.0 on 2019-12-30 03:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='comment.Comment'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.UUID('88bccd06-befc-463f-9533-8f8ecf1f58ce'), primary_key=True, serialize=False),
        ),
    ]
