# Generated by Django 3.0 on 2019-12-30 03:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20191230_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b94e6284-5c17-447a-858b-7fe544754bf7'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='upload',
            name='name',
            field=models.TextField(max_length=100),
        ),
    ]
