# Generated by Django 3.0 on 2019-12-30 12:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_auto_20191230_0317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='file',
            new_name='filepond',
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f2856f51-5676-4c1e-8c0a-81e1d7ff2b3c'), primary_key=True, serialize=False),
        ),
    ]
