# Generated by Django 3.0 on 2019-12-30 13:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_auto_20191230_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='filepond',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.UUIDField(default=uuid.UUID('28865f38-34cb-4acd-b727-36c2c31c69af'), primary_key=True, serialize=False),
        ),
    ]
