# Generated by Django 3.0 on 2019-12-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_auto_20191230_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
