# Generated by Django 3.0 on 2020-01-03 03:00

import commentbox.settings.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0009_auto_20191231_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='file',
            field=models.FileField(storage=commentbox.settings.storage_backends.UploadStorage, upload_to=''),
        ),
    ]
