# Generated by Django 3.0 on 2020-01-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0011_auto_20200103_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(blank=True, choices=[('SS', 'SS'), ('HRA', 'HRA'), ('TEST', 'TS')], default='', max_length=50),
        ),
    ]
